language: python

python:
  - "3.6"

cache: pip

install:
  - python3 -m pip install --quiet pipenv
  - pipenv install --dev --skip-lock


script:
  - pipenv run pylint docflow/

notifications:
  email: never

after_script:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh)"

